# Generated by Django 6.0.3 on 2026-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(verbose_name=())),
                ('category', models.CharField(max_length=60)),
            ],
        ),
    ]
