# Generated by Django 6.0.3 on 2026-03-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expenses',
            new_name='Expense',
        ),
    ]
